// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpaImNzHTCFfSIEG1XnSTarkem6L_fxEs',
    appId: '1:110145560500:web:d2b255f8c6ab59264e5ce1',
    messagingSenderId: '110145560500',
    projectId: 'safepath-campus',
    authDomain: 'safepath-campus.firebaseapp.com',
    storageBucket: 'safepath-campus.firebasestorage.app',
    measurementId: 'G-YHZT5P5ZZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-bLpha6Ikt8irjdaQ_UDvXLWCdhh3VaQ',
    appId: '1:110145560500:android:7f44b29e2eceeb184e5ce1',
    messagingSenderId: '110145560500',
    projectId: 'safepath-campus',
    storageBucket: 'safepath-campus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOog3L-BWhRHzdJ4sJJT7CJX3Llk2mjhk',
    appId: '1:110145560500:ios:c75132250e2b8c034e5ce1',
    messagingSenderId: '110145560500',
    projectId: 'safepath-campus',
    storageBucket: 'safepath-campus.firebasestorage.app',
    iosBundleId: 'com.example.safepathCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOog3L-BWhRHzdJ4sJJT7CJX3Llk2mjhk',
    appId: '1:110145560500:ios:c75132250e2b8c034e5ce1',
    messagingSenderId: '110145560500',
    projectId: 'safepath-campus',
    storageBucket: 'safepath-campus.firebasestorage.app',
    iosBundleId: 'com.example.safepathCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpaImNzHTCFfSIEG1XnSTarkem6L_fxEs',
    appId: '1:110145560500:web:6f803d73f49b46514e5ce1',
    messagingSenderId: '110145560500',
    projectId: 'safepath-campus',
    authDomain: 'safepath-campus.firebaseapp.com',
    storageBucket: 'safepath-campus.firebasestorage.app',
    measurementId: 'G-HD3C78LP5R',
  );
}
