// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9GoQrYPFdHLAHwYkeDn6Qn5VVFpCr_QA',
    appId: '1:685856606892:web:b94f3c15f2a9a3f8a06d09',
    messagingSenderId: '685856606892',
    projectId: 'safepathcampus',
    authDomain: 'safepathcampus.firebaseapp.com',
    storageBucket: 'safepathcampus.firebasestorage.app',
    measurementId: 'G-S6NBF3WGB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4n4ypb3r_sxVTftjJG7j-O_YP3RbgwXk',
    appId: '1:685856606892:android:bb1dbd2c492563a2a06d09',
    messagingSenderId: '685856606892',
    projectId: 'safepathcampus',
    storageBucket: 'safepathcampus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnHyheglNgFj7itR0N6Iy7WMAt3eE4dDU',
    appId: '1:685856606892:ios:d5460b73d4a3ecd4a06d09',
    messagingSenderId: '685856606892',
    projectId: 'safepathcampus',
    storageBucket: 'safepathcampus.firebasestorage.app',
    iosBundleId: 'com.example.safepathCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnHyheglNgFj7itR0N6Iy7WMAt3eE4dDU',
    appId: '1:685856606892:ios:d5460b73d4a3ecd4a06d09',
    messagingSenderId: '685856606892',
    projectId: 'safepathcampus',
    storageBucket: 'safepathcampus.firebasestorage.app',
    iosBundleId: 'com.example.safepathCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9GoQrYPFdHLAHwYkeDn6Qn5VVFpCr_QA',
    appId: '1:685856606892:web:3436809fd5afde38a06d09',
    messagingSenderId: '685856606892',
    projectId: 'safepathcampus',
    authDomain: 'safepathcampus.firebaseapp.com',
    storageBucket: 'safepathcampus.firebasestorage.app',
    measurementId: 'G-5YKNNTED8B',
  );

}
